# Generated by Django 4.1.1 on 2022-11-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept", models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "email",
                    models.CharField(
                        default="", max_length=30, primary_key=True, serialize=False
                    ),
                ),
                ("firstName", models.CharField(default="", max_length=30)),
                ("lastName", models.CharField(default="", max_length=30)),
                ("zoomLink", models.URLField(default="", max_length=300)),
                ("blurb", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=4)),
                ("catalog_number", models.CharField(max_length=4)),
                ("instructor", models.CharField(max_length=30)),
                ("section", models.CharField(max_length=4)),
                ("course_number", models.CharField(max_length=10)),
            ],
            options={
                "unique_together": {
                    (
                        "subject",
                        "catalog_number",
                        "instructor",
                        "section",
                        "course_number",
                    )
                },
            },
        ),
    ]
