# Generated by Django 4.2.dev20220919031901 on 2022-10-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="blurb",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(
                default="", max_length=30, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="firstName",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="user",
            name="lastName",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="user",
            name="zoomLink",
            field=models.URLField(default="", max_length=300),
        ),
    ]
