# Generated by Django 4.1.1 on 2022-11-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.TextField(default="section"),
        ),
    ]
