# Generated by Django 4.1.1 on 2022-11-01 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        default="Author of this post chose to be anonymous",
                        max_length=30,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        default="No topic was provided by the author of this post",
                        max_length=30,
                    ),
                ),
                ("startDate", models.DateField(default="2022-11-01")),
                ("endDate", models.DateField(default="2022-11-08")),
                (
                    "description",
                    models.TextField(
                        default="No description was provided by the author of this post"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studybuddy.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studybuddy.user",
                    ),
                ),
            ],
        ),
    ]
