# Generated by Django 4.1.1 on 2022-11-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0002_post_post_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="course", unique_together=set(),),
        migrations.AddField(
            model_name="course", name="description", field=models.TextField(default=""),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={
                (
                    "subject",
                    "catalog_number",
                    "instructor",
                    "section",
                    "course_number",
                    "description",
                )
            },
        ),
    ]
