# Generated by Django 4.1.1 on 2022-11-03 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0003_alter_post_enddate_alter_post_startdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="studybuddy.user"
            ),
        ),
    ]
