# Generated by Django 4.1.1 on 2022-11-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0003_user_major_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="firstName",
        ),
        migrations.RemoveField(
            model_name="user",
            name="lastName",
        ),
    ]
