# Generated by Django 4.1.1 on 2022-11-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0003_alter_course_unique_together_course_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="firstName",),
        migrations.RemoveField(model_name="user", name="lastName",),
        migrations.AddField(
            model_name="user",
            name="major",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
