# Generated by Django 4.1.1 on 2022-11-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0003_user_friends_friend_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=30),
        ),
    ]
