# Generated by Django 4.1.1 on 2022-11-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0004_message"),
        ("studybuddy", "0004_user_username"),
    ]

    operations = []
