# Generated by Django 4.1.1 on 2022-11-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0004_remove_user_firstname_remove_user_lastname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=20),
        ),
    ]
