# Generated by Django 4.1.1 on 2022-11-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0004_remove_user_firstname_remove_user_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='endDate',
            field=models.DateField(default='2022-11-14'),
        ),
        migrations.AlterField(
            model_name='post',
            name='startDate',
            field=models.DateField(default='2022-11-07'),
        ),
    ]
