# Generated by Django 4.1.3 on 2022-11-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0005_alter_post_enddate_alter_post_startdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Study Session", max_length=50)),
                ("start", models.TimeField(default="04-11")),
                ("end", models.TimeField(default="05-11")),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="endDate",
            field=models.DateField(default="2022-11-15"),
        ),
        migrations.AlterField(
            model_name="post",
            name="startDate",
            field=models.DateField(default="2022-11-08"),
        ),
    ]
