# Generated by Django 4.1.1 on 2022-11-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0005_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="major",
            field=models.TextField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.TextField(default="", max_length=50),
        ),
    ]
