# Generated by Django 4.1.1 on 2022-11-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0006_alter_user_major_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="major",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
