# Generated by Django 4.1.3 on 2022-11-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0006_studysession_alter_post_enddate_alter_post_startdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="studysession",
            name="date",
            field=models.DateField(default="2022-11-08"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="06-13"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="05-13"),
        ),
    ]
