# Generated by Django 4.1.3 on 2022-11-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0007_studysession_date_alter_studysession_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studysession",
            name="accepted",
            field=models.CharField(default="no", max_length=4),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="06-33"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="05-33"),
        ),
    ]
