# Generated by Django 4.1.3 on 2022-11-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0009_alter_studysession_end_alter_studysession_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studysession",
            name="accepted",
            field=models.CharField(default="?", max_length=4),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="13-50"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="12-50"),
        ),
    ]
