# Generated by Django 4.1.1 on 2022-11-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0010_alter_studysession_accepted_alter_studysession_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='endDate',
            field=models.DateField(default='2022-11-17'),
        ),
        migrations.AlterField(
            model_name='post',
            name='startDate',
            field=models.DateField(default='2022-11-10'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='date',
            field=models.DateField(default='2022-11-10'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='end',
            field=models.TimeField(default='17-57'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='start',
            field=models.TimeField(default='16-57'),
        ),
    ]
