# Generated by Django 4.1.3 on 2022-11-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "studybuddy",
            "0010_alter_studysession_accepted_alter_studysession_end_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="friend_request",
            name="declined",
            field=models.TextField(default="no", verbose_name="no"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="endDate",
            field=models.DateField(default="2022-11-18"),
        ),
        migrations.AlterField(
            model_name="post",
            name="startDate",
            field=models.DateField(default="2022-11-11"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="date",
            field=models.DateField(default="2022-11-11"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="17-59"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="16-59"),
        ),
    ]
