# Generated by Django 4.1.3 on 2022-11-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "studybuddy",
            "0010_alter_studysession_accepted_alter_studysession_end_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="endDate",
            field=models.DateField(default="2022-11-19"),
        ),
        migrations.AlterField(
            model_name="post",
            name="startDate",
            field=models.DateField(default="2022-11-12"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="date",
            field=models.DateField(default="2022-11-12"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="19-54"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="18-54"),
        ),
    ]
