# Generated by Django 4.1.1 on 2022-11-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0011_alter_post_enddate_alter_post_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='end',
            field=models.TimeField(default='22-13'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='start',
            field=models.TimeField(default='21-13'),
        ),
    ]
