# Generated by Django 4.1.1 on 2022-11-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0011_friend_request_declined_alter_post_enddate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="endDate",
            field=models.DateField(default="2022-11-20"),
        ),
        migrations.AlterField(
            model_name="post",
            name="startDate",
            field=models.DateField(default="2022-11-13"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="date",
            field=models.DateField(default="2022-11-13"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="01-38"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="00-38"),
        ),
    ]
