# Generated by Django 4.1.1 on 2022-11-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0012_alter_studysession_end_alter_studysession_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='endDate',
            field=models.DateField(default='2022-11-18'),
        ),
        migrations.AlterField(
            model_name='post',
            name='startDate',
            field=models.DateField(default='2022-11-11'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='date',
            field=models.DateField(default='2022-11-11'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='end',
            field=models.TimeField(default='00-30'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='start',
            field=models.TimeField(default='23-30'),
        ),
    ]
