# Generated by Django 4.1.3 on 2022-11-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0011_friend_request_declined_alter_post_enddate_and_more"),
        ("studybuddy", "0012_alter_studysession_end_alter_studysession_start"),
    ]

    operations = []
