# Generated by Django 4.1.1 on 2022-11-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0012_alter_post_enddate_alter_post_startdate_and_more"),
        ("studybuddy", "0013_merge_20221112_1958"),
    ]

    operations = []
