# Generated by Django 4.1.3 on 2022-11-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0013_merge_20221112_1958"),
    ]

    operations = [
        migrations.RemoveField(model_name="room", name="slug",),
        migrations.AddField(
            model_name="room",
            name="post",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="studybuddy.post",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="endDate",
            field=models.DateField(default="2022-11-20"),
        ),
        migrations.AlterField(
            model_name="post",
            name="startDate",
            field=models.DateField(default="2022-11-13"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="date",
            field=models.DateField(default="11-13-2022"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="17-07"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="16-07"),
        ),
    ]
