# Generated by Django 4.1.3 on 2022-11-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0014_remove_room_slug_room_post_alter_post_enddate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="users",
            field=models.ManyToManyField(to="studybuddy.user"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="17-30"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="16-30"),
        ),
    ]
