# Generated by Django 4.1.3 on 2022-11-13 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0015_room_users_alter_studysession_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="studybuddy.post"
            ),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="17-48"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="16-48"),
        ),
    ]
