# Generated by Django 4.1.3 on 2022-11-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0018_alter_studysession_end_alter_studysession_post_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studysession",
            name="users",
            field=models.ManyToManyField(to="studybuddy.user"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="19-32"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="18-32"),
        ),
    ]
