# Generated by Django 4.1.3 on 2022-11-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0014_merge_20221113_2011"),
        ("studybuddy", "0021_alter_studysession_end_alter_studysession_start"),
    ]

    operations = []
