# Generated by Django 4.1.3 on 2022-11-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0023_alter_studysession_date_alter_studysession_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="endDate",
            field=models.DateField(default="2022-11-21"),
        ),
        migrations.AlterField(
            model_name="post",
            name="startDate",
            field=models.DateField(default="2022-11-14"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="date",
            field=models.DateField(default="11-14-2022"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="14-14"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="13-14"),
        ),
    ]
