# Generated by Django 4.1.3 on 2022-11-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0025_studysession_author_alter_studysession_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="endDate",
            field=models.DateField(default="2022-11-22"),
        ),
        migrations.AlterField(
            model_name="post",
            name="startDate",
            field=models.DateField(default="2022-11-15"),
        ),
        migrations.AlterField(
            model_name="post",
            name="topic",
            field=models.CharField(
                default="No topic was provided by the author of this post",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="date",
            field=models.DateField(default="11-15-2022"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="16-53"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="15-53"),
        ),
    ]
