# Generated by Django 4.1.3 on 2022-11-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0026_alter_post_enddate_alter_post_startdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="16-55"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="15-55"),
        ),
    ]
