# Generated by Django 4.1.3 on 2022-11-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0027_alter_studysession_end_alter_studysession_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studysession",
            name="author",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="18-22"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="17-22"),
        ),
    ]
