# Generated by Django 4.1.1 on 2022-11-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "studybuddy",
            "0028_alter_studysession_author_alter_studysession_end_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="endDate",
            field=models.DateField(default="2022-11-27"),
        ),
        migrations.AlterField(
            model_name="post",
            name="startDate",
            field=models.DateField(default="2022-11-20"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="date",
            field=models.DateField(default="11-20-2022"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="04-32"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="03-32"),
        ),
        migrations.AlterField(
            model_name="user",
            name="major",
            field=models.CharField(default="", max_length=50),
        ),
    ]
