# Generated by Django 4.1.1 on 2022-11-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0029_alter_post_enddate_alter_post_startdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="04-35"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="03-35"),
        ),
    ]
