# Generated by Django 4.1.1 on 2022-11-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0030_alter_studysession_end_alter_studysession_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="00-07"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="23-07"),
        ),
    ]
